using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.EmailRecipientSendingStatusLookups
{
    public class EmailRecipientSendingStatusLookupManager : EmailRecipientSendingStatusLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public EmailRecipientSendingStatusLookupManager(IEmailRecipientSendingStatusLookupRepository emailRecipientSendingStatusLookupRepository)
            : base(emailRecipientSendingStatusLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}