using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Application.MadfoatcomRequests
{
    public class MadfoatcomRequest : MadfoatcomRequestBase
    {
        //<suite-custom-code-autogenerated>
        protected MadfoatcomRequest()
        {

        }

        public MadfoatcomRequest(int billerCode, bool feesOnBiller, string? billingNo = null, string? billNo = null, string? serviceType = null, string? prepaidCat = null, decimal? dueAmt = null, string? validationCode = null, string? jOEBPPSTrx = null, string? bankTrxId = null, string? bankCode = null, string? pmtStatus = null, decimal? paidAmt = null, decimal? feesAmt = null, DateTime? processDate = null, DateTime? stmtDate = null, string? accessChannel = null, string? paymentMethod = null, string? paymentType = null, decimal? amount = null, int? setBnkCode = null, string? acctNo = null, string? name = null, string? phone = null, string? address = null, string? email = null)
            : base(billerCode, feesOnBiller, billingNo, billNo, serviceType, prepaidCat, dueAmt, validationCode, jOEBPPSTrx, bankTrxId, bankCode, pmtStatus, paidAmt, feesAmt, processDate, stmtDate, accessChannel, paymentMethod, paymentType, amount, setBnkCode, acctNo, name, phone, address, email)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}