using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.MadfoatcomRequests
{
    public class MadfoatcomRequestManager : MadfoatcomRequestManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MadfoatcomRequestManager(IMadfoatcomRequestRepository madfoatcomRequestRepository)
            : base(madfoatcomRequestRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}