using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.ServiceTypeLookups
{
    public class ServiceTypeLookupManager : ServiceTypeLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ServiceTypeLookupManager(IServiceTypeLookupRepository serviceTypeLookupRepository)
            : base(serviceTypeLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}