using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.AccessChannelLookups
{
    public class AccessChannelLookupManager : AccessChannelLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AccessChannelLookupManager(IAccessChannelLookupRepository accessChannelLookupRepository)
            : base(accessChannelLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}