using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.MessageEncodingLookups
{
    public class MessageEncodingLookupManager : MessageEncodingLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MessageEncodingLookupManager(IMessageEncodingLookupRepository messageEncodingLookupRepository)
            : base(messageEncodingLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}