using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.PaymentStatusLookups
{
    public class PaymentStatusLookupManager : PaymentStatusLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PaymentStatusLookupManager(IPaymentStatusLookupRepository paymentStatusLookupRepository)
            : base(paymentStatusLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}