using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.BillingStatusLookups
{
    public class BillingStatusLookupManager : BillingStatusLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BillingStatusLookupManager(IBillingStatusLookupRepository billingStatusLookupRepository)
            : base(billingStatusLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}