using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Application.Permissions;
using Application.ServiceTypeLookups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Application.Shared;

namespace Application.ServiceTypeLookups
{
    public class ServiceTypeLookupsAppService : ServiceTypeLookupsAppServiceBase, IServiceTypeLookupsAppService
    {
        //<suite-custom-code-autogenerated>
        public ServiceTypeLookupsAppService(IServiceTypeLookupRepository serviceTypeLookupRepository, ServiceTypeLookupManager serviceTypeLookupManager, IDistributedCache<ServiceTypeLookupExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(serviceTypeLookupRepository, serviceTypeLookupManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}