using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Application.Permissions;
using Application.LanguageIsoNameLookups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Application.Shared;

namespace Application.LanguageIsoNameLookups
{
    public class LanguageIsoNameLookupsAppService : LanguageIsoNameLookupsAppServiceBase, ILanguageIsoNameLookupsAppService
    {
        //<suite-custom-code-autogenerated>
        public LanguageIsoNameLookupsAppService(ILanguageIsoNameLookupRepository languageIsoNameLookupRepository, LanguageIsoNameLookupManager languageIsoNameLookupManager, IDistributedCache<LanguageIsoNameLookupExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(languageIsoNameLookupRepository, languageIsoNameLookupManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}