using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Application.LanguageIsoNameLookups
{
    public class LanguageIsoNameLookup : LanguageIsoNameLookupBase
    {
        //<suite-custom-code-autogenerated>
        protected LanguageIsoNameLookup()
        {

        }

        public LanguageIsoNameLookup(string code, string name, string? description = null)
            : base(code, name, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}