using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.LanguageIsoNameLookups
{
    public class LanguageIsoNameLookupManager : LanguageIsoNameLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public LanguageIsoNameLookupManager(ILanguageIsoNameLookupRepository languageIsoNameLookupRepository)
            : base(languageIsoNameLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}