using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.PaymentCurrencyLookups
{
    public class PaymentCurrencyLookupManager : PaymentCurrencyLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PaymentCurrencyLookupManager(IPaymentCurrencyLookupRepository paymentCurrencyLookupRepository)
            : base(paymentCurrencyLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}