using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.PaymentSourceLookups
{
    public class PaymentSourceLookupManager : PaymentSourceLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PaymentSourceLookupManager(IPaymentSourceLookupRepository paymentSourceLookupRepository)
            : base(paymentSourceLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}