using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.BillTypeLookups
{
    public class BillTypeLookupManager : BillTypeLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BillTypeLookupManager(IBillTypeLookupRepository billTypeLookupRepository)
            : base(billTypeLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}