using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.ProcessStatusLookups
{
    public class ProcessStatusLookupManager : ProcessStatusLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ProcessStatusLookupManager(IProcessStatusLookupRepository processStatusLookupRepository)
            : base(processStatusLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}