using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.MethodTypeLookups
{
    public class MethodTypeLookupManager : MethodTypeLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MethodTypeLookupManager(IMethodTypeLookupRepository methodTypeLookupRepository)
            : base(methodTypeLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}