using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.BillStatusLookups
{
    public class BillStatusLookupManager : BillStatusLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BillStatusLookupManager(IBillStatusLookupRepository billStatusLookupRepository)
            : base(billStatusLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}