using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Application.Permissions;
using Application.BillStatusLookups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Application.Shared;

namespace Application.BillStatusLookups
{
    public class BillStatusLookupsAppService : BillStatusLookupsAppServiceBase, IBillStatusLookupsAppService
    {
        //<suite-custom-code-autogenerated>
        public BillStatusLookupsAppService(IBillStatusLookupRepository billStatusLookupRepository, BillStatusLookupManager billStatusLookupManager, IDistributedCache<BillStatusLookupExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(billStatusLookupRepository, billStatusLookupManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}