using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Application.Permissions;
using Application.OperationTypeLookups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Application.Shared;

namespace Application.OperationTypeLookups
{
    public class OperationTypeLookupsAppService : OperationTypeLookupsAppServiceBase, IOperationTypeLookupsAppService
    {
        //<suite-custom-code-autogenerated>
        public OperationTypeLookupsAppService(IOperationTypeLookupRepository operationTypeLookupRepository, OperationTypeLookupManager operationTypeLookupManager, IDistributedCache<OperationTypeLookupExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(operationTypeLookupRepository, operationTypeLookupManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}