using System;

namespace Application.EmailRecipientSendingStatusLookups;

[Serializable]
public class EmailRecipientSendingStatusLookupExcelDownloadTokenCacheItem : EmailRecipientSendingStatusLookupExcelDownloadTokenCacheItemBase
{
}