using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Application.Permissions;
using Application.EmailRecipientSendingStatusLookups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Application.Shared;

namespace Application.EmailRecipientSendingStatusLookups
{
    public class EmailRecipientSendingStatusLookupsAppService : EmailRecipientSendingStatusLookupsAppServiceBase, IEmailRecipientSendingStatusLookupsAppService
    {
        //<suite-custom-code-autogenerated>
        public EmailRecipientSendingStatusLookupsAppService(IEmailRecipientSendingStatusLookupRepository emailRecipientSendingStatusLookupRepository, EmailRecipientSendingStatusLookupManager emailRecipientSendingStatusLookupManager, IDistributedCache<EmailRecipientSendingStatusLookupExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(emailRecipientSendingStatusLookupRepository, emailRecipientSendingStatusLookupManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}