using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.CharSetLookups
{
    public class CharSetLookupManager : CharSetLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CharSetLookupManager(ICharSetLookupRepository charSetLookupRepository)
            : base(charSetLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}