using System;

namespace Application.OrangeBillPullServiceConfigurations;

[Serializable]
public class OrangeBillPullServiceConfigurationExcelDownloadTokenCacheItem : OrangeBillPullServiceConfigurationExcelDownloadTokenCacheItemBase
{
}