using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.OperationTypeLookups
{
    public class OperationTypeLookupManager : OperationTypeLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public OperationTypeLookupManager(IOperationTypeLookupRepository operationTypeLookupRepository)
            : base(operationTypeLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}