using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.PaymentTypeLookups
{
    public class PaymentTypeLookupManager : PaymentTypeLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PaymentTypeLookupManager(IPaymentTypeLookupRepository paymentTypeLookupRepository)
            : base(paymentTypeLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}