using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.MadfoatcomResponses
{
    public class MadfoatcomResponseManager : MadfoatcomResponseManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MadfoatcomResponseManager(IMadfoatcomResponseRepository madfoatcomResponseRepository)
            : base(madfoatcomResponseRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}