using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Application.MadfoatcomResponses
{
    public class MadfoatcomResponse : MadfoatcomResponseBase
    {
        //<suite-custom-code-autogenerated>
        protected MadfoatcomResponse()
        {

        }

        public MadfoatcomResponse(bool allowPart, int? billerCode = null, string? billingNo = null, string? billNo = null, string? dueAmt = null, string? validationCode = null, string? serviceType = null, string? prepaidCat = null, string? amount = null, int? setBnkCode = null, string? acctNo = null, string? transferReason = null, string? receivingCountry = null, string? custName = null, string? email = null, string? phone = null, int? recCount = null, string? billStatus = null, string? dueAmount = null, DateTime? issueDate = null, DateTime? openDate = null, DateTime? dueDate = null, DateTime? expiryDate = null, DateTime? closeDate = null, string? billType = null, string? upper = null, string? lower = null, int? billsCount = null, string? jOEBPPSTrx = null, DateTime? processDate = null, string? sTMTDate = null)
            : base(allowPart, billerCode, billingNo, billNo, dueAmt, validationCode, serviceType, prepaidCat, amount, setBnkCode, acctNo, transferReason, receivingCountry, custName, email, phone, recCount, billStatus, dueAmount, issueDate, openDate, dueDate, expiryDate, closeDate, billType, upper, lower, billsCount, jOEBPPSTrx, processDate, sTMTDate)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}