using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.PrepaidCategoryLookups
{
    public class PrepaidCategoryLookupManager : PrepaidCategoryLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PrepaidCategoryLookupManager(IPrepaidCategoryLookupRepository prepaidCategoryLookupRepository)
            : base(prepaidCategoryLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}