using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Application.Permissions;
using Application.PaymentSourceLookups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Application.Shared;

namespace Application.PaymentSourceLookups
{
    public class PaymentSourceLookupsAppService : PaymentSourceLookupsAppServiceBase, IPaymentSourceLookupsAppService
    {
        //<suite-custom-code-autogenerated>
        public PaymentSourceLookupsAppService(IPaymentSourceLookupRepository paymentSourceLookupRepository, PaymentSourceLookupManager paymentSourceLookupManager, IDistributedCache<PaymentSourceLookupExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(paymentSourceLookupRepository, paymentSourceLookupManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}