using System;

namespace Application.OrangeBillPaymentNotificationConfigurations;

[Serializable]
public class OrangeBillPaymentNotificationConfigurationExcelDownloadTokenCacheItem : OrangeBillPaymentNotificationConfigurationExcelDownloadTokenCacheItemBase
{
}