using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.SeverityLookups
{
    public class SeverityLookupManager : SeverityLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SeverityLookupManager(ISeverityLookupRepository severityLookupRepository)
            : base(severityLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}