using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Application.PrepaidValidationConfigs
{
    public class PrepaidValidationConfig : PrepaidValidationConfigBase
    {
        //<suite-custom-code-autogenerated>
        protected PrepaidValidationConfig()
        {

        }

        public PrepaidValidationConfig(string serviceType, bool isTesting, string? channelCode = null, string? billingName = null, string? aliasBillingName = null, string? endpointUrl = null)
            : base(serviceType, isTesting, channelCode, billingName, aliasBillingName, endpointUrl)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}