using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.PrepaidValidationConfigs
{
    public class PrepaidValidationConfigManager : PrepaidValidationConfigManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PrepaidValidationConfigManager(IPrepaidValidationConfigRepository prepaidValidationConfigRepository)
            : base(prepaidValidationConfigRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}