using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.OrangeBillPaymentNotificationConfigurations
{
    public class OrangeBillPaymentNotificationConfigurationManager : OrangeBillPaymentNotificationConfigurationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public OrangeBillPaymentNotificationConfigurationManager(IOrangeBillPaymentNotificationConfigurationRepository orangeBillPaymentNotificationConfigurationRepository)
            : base(orangeBillPaymentNotificationConfigurationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}