using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.ThresholdLookups
{
    public class ThresholdLookupManager : ThresholdLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ThresholdLookupManager(IThresholdLookupRepository thresholdLookupRepository)
            : base(thresholdLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}