using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Application.OrangeBillPullServiceConfigurations
{
    public class OrangeBillPullServiceConfiguration : OrangeBillPullServiceConfigurationBase
    {
        //<suite-custom-code-autogenerated>
        protected OrangeBillPullServiceConfiguration()
        {

        }

        public OrangeBillPullServiceConfiguration(int serviceTypeId, bool isServiceEnabled, bool isWebServiceEnabled, string webServiceUrl, string? storedProcedureName = null, string? billerCode = null, string? connectionStringUserId = null, string? connectionStringPassword = null, string? connectionStringDataSource = null, string? logLevel = null, int? severityId = null, int? dailyLimit = null, int? weeklyLimit = null, int? monthlyLimit = null, int? yearlyLimit = null, string? errorMessage = null)
            : base(serviceTypeId, isServiceEnabled, isWebServiceEnabled, webServiceUrl, storedProcedureName, billerCode, connectionStringUserId, connectionStringPassword, connectionStringDataSource, logLevel, severityId, dailyLimit, weeklyLimit, monthlyLimit, yearlyLimit, errorMessage)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}