using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.OrangeBillPullServiceConfigurations
{
    public class OrangeBillPullServiceConfigurationManager : OrangeBillPullServiceConfigurationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public OrangeBillPullServiceConfigurationManager(IOrangeBillPullServiceConfigurationRepository orangeBillPullServiceConfigurationRepository)
            : base(orangeBillPullServiceConfigurationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}