using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Application.Permissions;
using Application.ThresholdLookups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Application.Shared;

namespace Application.ThresholdLookups
{
    public class ThresholdLookupsAppService : ThresholdLookupsAppServiceBase, IThresholdLookupsAppService
    {
        //<suite-custom-code-autogenerated>
        public ThresholdLookupsAppService(IThresholdLookupRepository thresholdLookupRepository, ThresholdLookupManager thresholdLookupManager, IDistributedCache<ThresholdLookupExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(thresholdLookupRepository, thresholdLookupManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}