using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.PaymentMethodLookups
{
    public class PaymentMethodLookupManager : PaymentMethodLookupManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PaymentMethodLookupManager(IPaymentMethodLookupRepository paymentMethodLookupRepository)
            : base(paymentMethodLookupRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}