using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Application.ApiRequestResponseLogs
{
    public class ApiRequestResponseLogManager : ApiRequestResponseLogManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ApiRequestResponseLogManager(IApiRequestResponseLogRepository apiRequestResponseLogRepository)
            : base(apiRequestResponseLogRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}