using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Application.ApiRequestResponseLogs
{
    public class ApiRequestResponseLog : ApiRequestResponseLogBase
    {
        //<suite-custom-code-autogenerated>
        protected ApiRequestResponseLog()
        {

        }

        public ApiRequestResponseLog(bool isSuccessful, string? requestUrl = null, string? requestMethod = null, string? requestHeaders = null, string? requestBody = null, string? responseBody = null, int? responseStatusCode = null, string? responseHeaders = null, int? durationMs = null, DateTime? createdAt = null, string? correlationId = null, string? ipAddress = null, string? userId = null, string? errorDetails = null, string? sourceSystem = null)
            : base(isSuccessful, requestUrl, requestMethod, requestHeaders, requestBody, responseBody, responseStatusCode, responseHeaders, durationMs, createdAt, correlationId, ipAddress, userId, errorDetails, sourceSystem)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}