using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Application.Permissions;
using Application.PaymentMethodLookups;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Application.Shared;

namespace Application.PaymentMethodLookups
{
    public class PaymentMethodLookupsAppService : PaymentMethodLookupsAppServiceBase, IPaymentMethodLookupsAppService
    {
        //<suite-custom-code-autogenerated>
        public PaymentMethodLookupsAppService(IPaymentMethodLookupRepository paymentMethodLookupRepository, PaymentMethodLookupManager paymentMethodLookupManager, IDistributedCache<PaymentMethodLookupExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(paymentMethodLookupRepository, paymentMethodLookupManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}